#!/bin/bash

# Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

build_all()
{
    if [ "$#" = 0 ]; then
        set -- [0-9][0-9]*
    fi

    for i; do
        i=$(basename $i)
        IMAGE=${i##[0-9][0-9]-}
        FULL_IMAGE=$REPO/bos-$IMAGE:$TAG

        cd $i
        if [ -e archs ] && ! grep -w -q $ARCH archs; then
            echo skipping $FULL_IMAGE for $ARCH
            cd ..
            continue
        fi

        echo building $FULL_IMAGE
        ROOT=.
        if [ -e root ]; then
            ROOT=$(readlink -f root)
        fi
        docker build --build-arg TAG=$TAG --build-arg VERSION=${VERSION} --build-arg REPO=${REPO} --build-arg ARCH=${ARCH} -f $(pwd)/Dockerfile -t $FULL_IMAGE $ROOT
        cd ..
    done
}

copy_all()
{
    OUTPUT=$1
    shift

    if [ "$#" = 0 ]; then
        set -- [0-9][0-9]*
    fi

    for i; do
        i=$(basename $i)
        IMAGE=${i##[0-9][0-9]-}
        FULL_IMAGE=$REPO/bos-$IMAGE:$TAG

        cd $i
        if [ -e archs ] && ! grep -w -q $ARCH archs; then
            echo skipping $FULL_IMAGE for $ARCH
            cd ..
            continue
        fi

        echo building $FULL_IMAGE
        ID=$(docker create $FULL_IMAGE)
        echo $(readlink -f ${OUTPUT})
        rm -rf output
        docker cp ${ID}:/output .
        docker rm -fv $ID
        cp ./output/* ${OUTPUT}/
        rm -rf ./output
        cd ..
    done
}