#!/bin/bash

# Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

source $(dirname $0)/version
source $(dirname $0)/images

cd $(dirname $0)/..

DIST=$(pwd)/dist/artifacts

pushd images/output
build_all "$@"
mkdir -p ${DIST}
copy_all ${DIST} "$@"
popd

mkdir -p ./build
ID=$(docker create ${REPO}/bos-package:${TAG})
docker cp ${ID}:/output/bos ./build/
docker rm -fv $ID

docker build \
  --build-arg ARCH=${ARCH} \
  --build-arg REPO=${REPO} \
  --build-arg TAG=${TAG} \
  --build-arg VERSION=${VERSION} \
  --file package/Dockerfile \
  --tag ${REPO}/bos:${TAG} \
  --tag ${REPO}/bos:latest \
.
docker image save --output ./dist/images.tar \
  ${REPO}/bos:${TAG} \
  ${REPO}/bos:latest
echo ${REPO}/bos:${TAG} > ./dist/images.txt
echo Built ${REPO}/bos:${TAG}