#!/bin/bash

setup_ssh()
{
    if [ ! -e /var/lib/bhojpur/os/ssh ]; then
        mkdir -p /var/lib/bhojpur/os
        cp -rf /etc/ssh /var/lib/bhojpur/os/ssh
    fi
    rm -rf /etc/ssh
    ln -s /var/lib/bhojpur/os/ssh /etc/ssh
}

setup_bhojpur_node()
{
    mkdir -p /etc/bhojpur
    mkdir -p /var/lib/bhojpur/os/node
    ln -s /var/lib/bhojpur/os/node /etc/bhojpur/
}

setup_ssh
setup_bhojpur_node